# Generated by Django 5.2.8 on 2026-01-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='image_background',
            field=models.ImageField(blank=True, null=True, upload_to='img/background'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='image_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='img/favicon'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='image_login_banner',
            field=models.ImageField(blank=True, null=True, upload_to='img/login_banner'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='image_logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/logo'),
        ),
    ]
