# Generated by Django 5.2.8 on 2026-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='JPG ou PNG. Tamanho máximo de 1MB.', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
